[tool.poetry]
name = "styringsinfo-datafortelling"
packages = [{ include = "figurer", from = "src" }]
version = "0.1.0"
description = ""
authors = ["NAV"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
google-cloud-bigquery = "3.11.0"
ipykernel = "6.22.0"
nbclient = "0.8.0"
pandas = "2.0.3"
db-dtypes = "1.1.1"
python-dotenv = "1.0.0"
tabulate = "0.9.0"
plotly = "5.15.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
