apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: styringsinfo-datafortelling-alerts
  namespace: tbd
  labels:
    team: tbd
spec:
  groups:
    - name: styringsinfo-datafortelling-alerts
      rules:
        - alert: NaisjobFailed
          expr: kube_job_failed{job_name=~"^styringsinfo-datafortelling.*", namespace="tbd"} > 0
          for: 2m
          annotations:
            consequence: "Datafortelling https://{{dataplattformUrl}}/quarto/{{quartoId}}/ blir ikke oppdatert"
            action: "@sp-styringsinfo-bros - Sjekk https://logs.adeo.no/app/r/s/lU1a0"
            summary: |-
              NaisJob styringsinfo-datafortelling feiler i {{environment}} - datafortellingen oppdateres ikke. 
              Repo: https://github.com/navikt/helse-styringsinfo-datafortelling
              Alert: https://github.com/navikt/helse-styringsinfo-datafortelling/blob/main/deploy/alerts.yml
          labels:
            namespace: tbd
            severity: warning
            sykepenger_styringsinfo_type_datafortelling: {{environment}}-alert
            alert_type: custom

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sykepenger-styringsinfo-{{environment}}-slack-datafortelling
  namespace: tbd
  labels:
    team: tbd
    alertmanagerConfig: sykepenger-styringsinfo-{{environment}}-slack-datafortelling
spec:
  receivers:
    - name: sykepenger-styringsinfo-{{environment}}-receiver-datafortelling
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: "{{alertChannel}}"
          iconEmoji: ':alert:'
          username: 'Alert {{environment}}-gcp'
          sendResolved: true
          title: |-
            [\{{ .Status | toUpper }}\{{ if eq .Status "firing" }}:\{{ .Alerts.Firing | len }}\{{ end }}] \{{ .CommonLabels.alertname }}
          text: >-
            \{{ range .Alerts }}
            \{{ if or .Annotations.summary .Annotations.message }}
            \{{ or .Annotations.summary .Annotations.message }}
            \{{ println " " }}
            \{{- end }}
            \{{- if .Annotations.action }}
            • *action*: \{{ .Annotations.action }} \{{ println " " }}
            \{{- end }}
            \{{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "sykepenger_styringsinfo_type_datafortelling"
        matchType: "="
        value: "{{environment}}-alert"
    groupInterval: 10s
    groupWait: 5s
    receiver: sykepenger-styringsinfo-{{environment}}-receiver-datafortelling
    repeatInterval: 2h