apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: helse-styringsinfo-datafortelling-alerts
  namespace: tbd
  labels:
    team: tbd
spec:
  groups:
    - name: helse-styringsinfo-datafortelling-alerts
      rules:
        - alert: NaisjobFailed
          expr: kube_job_failed{job_name=~"^helse-styringsinfo-datafortelling.*", namespace="tbd"} > 0
          for: 2m
          annotations:
            consequence: "Datafortelling https://data.intern.dev.nav.no/quarto/f9a63635-60dc-4fb0-87aa-104f18e0e3e2/ blir ikke oppdatert"
            action: "@sp-styringsinfo-bros - Sjekk https://logs.adeo.no/app/r/s/lU1a0 (dette er dev)"
            summary: |-
              NaisJob helse-styringsinfo-datafortelling feiler i dev-gcp:tbd - datafortellingen oppdateres ikke. 
              Repo: https://github.com/navikt/helse-styringsinfo-datafortelling
              Alert: https://github.com/navikt/helse-styringsinfo-datafortelling/blob/main/deploy/alerts.yml
          labels:
            namespace: tbd
            severity: warning
            sykepenger_styringsinfo_type_datafortelling: dev-alert
            alert_type: custom

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: helse-styringsinfo-dev-slack-datafortelling
  namespace: tbd
  labels:
    team: tbd
    alertmanagerConfig: helse-styringsinfo-dev-slack-datafortelling
spec:
  receivers:
    - name: helse-styringsinfo-dev-receiver-datafortelling
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#sykepenger-styringsinfo-dev'
          iconEmoji: ':alert:'
          username: 'Alert dev-gcp'
          sendResolved: true
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}
            {{ if or .Annotations.summary .Annotations.message }}
            {{ or .Annotations.summary .Annotations.message }}
            {{ println " " }}
            {{- end }}
            {{- if .Annotations.action }}
            • *action*: {{ .Annotations.action }} {{ println " " }}
            {{- end }}
            {{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "helse_styringsinfo_type_datafortelling"
        matchType: "="
        value: "dev-alert"
    groupInterval: 10s
    groupWait: 5s
    receiver: helse-styringsinfo-dev-receiver-datafortelling
    repeatInterval: 2h