apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: tbd
  name: styringsinfo-datafortelling
  namespace: tbd
spec:
  image: {{image}}
  schedule: "0 */1 * * *"
  backoffLimit: 0
  secureLogs:
    enabled: true
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-dev-7ff9
        role: roles/bigquery.dataViewer
  accessPolicy:
    outbound:
      external:
      - host: nada.ekstern.dev.nav.no