apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: tbd
  name: styringsinfo-datafortelling
  namespace: tbd
spec:
  image: {{image}}
  schedule: "0 */1 * * *"
  env:
    - name: NADA_URL:
      value: nada.dev.intern.nav.no
    - name: QUARTO_ID:
    value: 29726852-4afe-42da-a3a4-c932d6234fb6
  envFrom:
    - secret: nada-token

  backoffLimit: 0
  secureLogs:
    enabled: true
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-dev-7ff9
        role: roles/bigquery.dataViewer
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-dev-7ff9
        role: roles/bigquery.jobUser
  accessPolicy:
    outbound:
      external:
      - host: nada.dev.intern.no
