apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: tbd
  name: styringsinfo-datafortelling{{#if schedule}}{{else}}-run-on-deploy{{/if}}
  namespace: tbd
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{image}}
  {{#if schedule}}
  schedule: {{schedule}}
  {{/if}}
  env:
    - name: NADA_URL
      value: nada.intern.nav.no
    - name: QUARTO_ID
      value: 4e2185aa-2415-449a-8d4f-99af890272ca
    - name: GCP_TEAM_PROJECT_ID
      value: tbd-prod-eacd
  envFrom:
    - secret: nada-token

  backoffLimit: 0
  concurrencyPolicy: Replace
  secureLogs:
    enabled: true
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-prod-eacd
        role: roles/bigquery.readSessionUser
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-prod-eacd
        role: roles/bigquery.dataViewer
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-prod-eacd
        role: roles/bigquery.jobUser
  accessPolicy:
    outbound:
      external:
      - host: nada.intern.nav.no
