name: Deploy alerts
on:
  push:
    branches:
      - main
    paths:
      - 'deploy/alerts.yml'
      - '.github/workflows/alerts.yml'

jobs:
  apply-alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/alerts.yaml

